# Generated by Django 5.0.3 on 2024-04-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0019_examstatus_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='optionA_slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='optionB_slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='optionC_slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='optionD_slug',
            field=models.SlugField(),
        ),
    ]
