# Generated by Django 5.0.3 on 2024-04-10 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EECommittee', '0005_alter_course_description'),
        ('instructor', '0020_alter_testquestion_optiona_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamStatus',
            new_name='ModelExamStatus',
        ),
        migrations.CreateModel(
            name='TestExamStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=255)),
                ('response_status', models.CharField(max_length=255)),
                ('question_category', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testexamstatus', to='EECommittee.department')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_exam_status', to='instructor.testquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_exam_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
