# Generated by Django 5.0.3 on 2024-04-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EECommittee', '0003_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
